# Generated by Django 5.2 on 2025-04-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
