# Generated by Django 5.2 on 2025-04-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_objective_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
