# Generated by Django 5.2 on 2025-04-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
